import { GeminiToolDispatcher } from './tool-dispatcher.js';
import type { MediaProvider } from '../providers/types.js';
import type { ToolContext } from './tool-dispatcher.js';
const requiredString = (args: Record<string, unknown>, key: string) => { const value = args[key]; if (typeof value !== 'string' || !value.trim()) throw new Error(`${key} is required`); return value.trim(); };
const optionalAssetIds = (args: Record<string, unknown>) => { if (args.asset_ids === undefined) return []; if (!Array.isArray(args.asset_ids) || !args.asset_ids.every(id => typeof id === 'string')) throw new Error('asset_ids must be an array of strings'); return args.asset_ids as string[]; };
const requiredAssetIds = (args: Record<string, unknown>) => { const ids = optionalAssetIds(args); if (!ids.length) throw new Error('asset_ids must contain at least one asset'); return ids; };
export interface JobGateway { create(input: { userId: string; intent: string; prompt: string; creditsReserved: number; reference: string; telegramChatId?: string; telegramStatusMessageId?: number; conversationId?: string; sourceAssetIds?: string[] }): Promise<{ jobId: string }>; updateStatus?(input: { jobId: string; status: 'queued' | 'analyzing' | 'processing' | 'generating' | 'rendering' | 'uploading' | 'completed' | 'failed' | 'cancelled'; progress?: number; provider?: string; providerJobId?: string; outputAssets?: unknown; outputUrl?: string; error?: string }): Promise<void>; failAndRefund(jobId: string, reason: string): Promise<void>; }
export function registerMediaTools(dispatcher: GeminiToolDispatcher, deps: { videoProvider: MediaProvider; imageProvider?: MediaProvider; audioProvider?: MediaProvider; jobs: JobGateway; videoCredits?: number; imageCredits?: number; audioCredits?: number }) {
  const queue = async (args: Record<string, unknown>, context: ToolContext, provider: MediaProvider | undefined, intent: string, credits: number, defaultMessage: string, ids?: string[]) => {
    const prompt = requiredString(args, 'prompt'); if (!provider) return { status: 'provider_required', operation: intent, prompt };
    const requestedIds = ids ?? optionalAssetIds(args); const available = context.assets ?? []; const selected = requestedIds.length ? available.filter(asset => requestedIds.includes(asset.id)) : available;
    if (requestedIds.length && selected.length !== requestedIds.length) throw new Error('One or more requested media assets are not available in the current conversation');
    const capability = intent === 'image_generation' || intent === 'image_edit' ? 'imageGeneration' : intent === 'audio_generation' || intent === 'transcription' ? 'audioGeneration' : null;
    if (capability && !provider.capabilities[capability]) return { status: 'provider_required', operation: intent, prompt };
    const created = await deps.jobs.create({ userId: context.userId, intent, prompt, creditsReserved: credits, reference: `gemini:${context.userId}:${context.requestId ?? 'request'}:${intent}`, telegramChatId: context.chatId, telegramStatusMessageId: context.statusMessageId, conversationId: context.conversationId, sourceAssetIds: selected.map(asset => asset.id) });
    return { status: 'queued', jobId: created.jobId, operation: intent, provider: provider.name, progress: 0, message: defaultMessage };
  };
  dispatcher.register('generate_video', async (args, context) => { const prompt = requiredString(args, 'prompt'); const requestedIds = optionalAssetIds(args); const available = context.assets ?? []; const selected = requestedIds.length ? available.filter(asset => requestedIds.includes(asset.id)) : available.filter(asset => asset.type === 'image'); if (requestedIds.length && selected.length !== requestedIds.length) throw new Error('One or more requested media assets are not available in the current conversation'); if (!selected.some(asset => asset.type === 'image')) return { status: 'provider_required', operation: 'text_to_video', prompt }; const created = await deps.jobs.create({ userId: context.userId, intent: 'image_to_video', prompt, creditsReserved: deps.videoCredits ?? 30, reference: `gemini:${context.userId}:${context.requestId ?? 'request'}:image_to_video`, telegramChatId: context.chatId, telegramStatusMessageId: context.statusMessageId, conversationId: context.conversationId, sourceAssetIds: selected.map(asset => asset.id) }); return { status: 'queued', jobId: created.jobId, operation: 'image_to_video', provider: deps.videoProvider.name, progress: 0, message: 'Video generation has been queued. The background worker will generate and deliver it to Telegram.' }; });
  dispatcher.register('generate_image', async (args, context) => queue(args, context, deps.imageProvider, 'image_generation', deps.imageCredits ?? 5, 'Image generation has been queued.'));
  dispatcher.register('edit_image', async (args, context) => queue({ ...args, prompt: requiredString(args, 'prompt') }, context, deps.imageProvider, 'image_edit', deps.imageCredits ?? 5, 'Image editing has been queued.', requiredAssetIds(args)));
  dispatcher.register('generate_voice', async (args, context) => queue(args, context, deps.audioProvider, 'audio_generation', deps.audioCredits ?? 5, 'Voice generation has been queued.'));
  dispatcher.register('transcribe_audio', async (args, context) => queue({ prompt: `Transcribe audio${typeof args.language === 'string' ? ` in ${args.language}` : ''}.`, asset_ids: [requiredString(args, 'asset_id')] }, context, deps.audioProvider, 'transcription', 2, 'Transcription has been queued.', [requiredString(args, 'asset_id')]));
  dispatcher.register('edit_video', async (args) => ({ status: 'planned', operation: 'video_edit', instructions: requiredString(args, 'instructions'), assetIds: requiredAssetIds(args) }));
  dispatcher.register('analyze_document', async (args) => ({ status: 'provider_required', operation: 'document_analysis', assetId: requiredString(args, 'asset_id'), question: typeof args.question === 'string' ? args.question : null }));
  dispatcher.register('convert_media', async (args) => ({ status: 'worker_required', operation: 'convert_media', assetId: requiredString(args, 'asset_id'), targetFormat: requiredString(args, 'target_format'), quality: typeof args.quality === 'string' ? args.quality : null }));
}
