import 'dotenv/config';
import { config } from './config.js';
import { ConfiguredVideoProvider } from './providers/configured-video.js';
import { ConfiguredGenericProvider } from './providers/configured-generic.js';
import { S3MediaStorage } from './storage/s3.js';
import { TelegramApi } from './telegram/api.js';
import type { MediaAsset } from './gemini/types.js';
import type { MediaProvider } from './providers/types.js';

type WorkerJob = { _id: string; userId: string; telegramChatId?: string; telegramStatusMessageId?: number; status: string; prompt: string; intent: string; progress: number; sourceAssetIds?: string[] };
type WorkerAsset = { _id: string; storageKey?: string; type: MediaAsset['type']; mimeType: string; telegramFileId?: string };
class WorkerGateway { constructor(private readonly baseUrl: string, private readonly secret: string) {} private async post<T>(path: string, body: unknown): Promise<T> { const response = await fetch(`${this.baseUrl.replace(/\/$/, '')}${path}`, { method: 'POST', headers: { 'content-type': 'application/json', 'x-agent-secret': this.secret }, body: JSON.stringify(body) }); const text = await response.text(); if (!response.ok) throw new Error(`Worker gateway ${response.status}: ${text}`); return JSON.parse(text) as T; } claim() { return this.post<{ job: WorkerJob | null; assets: WorkerAsset[] }>('/agent/jobs/claim', {}); } status(input: { jobId: string; status: 'processing' | 'generating' | 'rendering' | 'uploading' | 'completed'; progress?: number; provider?: string; providerJobId?: string; outputUrl?: string; outputAssets?: unknown }) { return this.post('/agent/jobs/status', input); } fail(jobId: string, reason: string) { return this.post('/agent/jobs/fail', { jobId, reason }); } }
const gateway = new WorkerGateway(config.CONVEX_URL!, config.AGENT_GATEWAY_SECRET!);
const providers: Record<string, MediaProvider> = {
  image_generation: new ConfiguredGenericProvider('configured-image-provider', config.IMAGE_PROVIDER_ENDPOINT, config.IMAGE_PROVIDER_API_KEY, { imageGeneration: Boolean(config.IMAGE_PROVIDER_API_KEY), imageEditing: Boolean(config.IMAGE_PROVIDER_API_KEY), imageToVideo: false, textToVideo: false, videoEditing: false, audioGeneration: false, transcription: false, upscaling: false }),
  audio_generation: new ConfiguredGenericProvider('configured-audio-provider', config.AUDIO_PROVIDER_ENDPOINT, config.AUDIO_PROVIDER_API_KEY, { imageGeneration: false, imageEditing: false, imageToVideo: false, textToVideo: false, videoEditing: false, audioGeneration: Boolean(config.AUDIO_PROVIDER_API_KEY), transcription: false, upscaling: false }),
  image_to_video: new ConfiguredVideoProvider(config.VIDEO_PROVIDER_ENDPOINT), text_to_video: new ConfiguredVideoProvider(config.VIDEO_PROVIDER_ENDPOINT)
};
const storage = new S3MediaStorage(); const telegram = new TelegramApi();
async function progress(job: WorkerJob, text: string) { if (job.telegramChatId && job.telegramStatusMessageId) { try { await telegram.editMessage(job.telegramChatId, job.telegramStatusMessageId, text); } catch (error) { console.warn('Telegram progress update failed:', error); } } }
async function processJob(job: WorkerJob, sourceAssets: WorkerAsset[]) {
  const provider = providers[job.intent]; if (!provider) throw new Error(`Unsupported worker intent: ${job.intent}`);
  await gateway.status({ jobId: job._id, status: 'processing', progress: 5, provider: provider.name });
  await progress(job, `🔍 Preparing your ${job.intent === 'image_generation' ? 'image' : job.intent === 'audio_generation' ? 'voice' : 'video'}...\n\n░░░░░░░░░░ 5%`);
  const assets: MediaAsset[] = [];
  for (const asset of sourceAssets) { if (!asset.storageKey) continue; const uri = await storage.signedGetUrl(asset.storageKey, 900); assets.push({ id: String(asset._id), type: asset.type, mimeType: asset.mimeType, telegramFileId: asset.telegramFileId, storageKey: asset.storageKey, uri }); }
  const created = await provider.create({ operation: job.intent, prompt: job.prompt, assets, options: { jobId: job._id } });
  await gateway.status({ jobId: job._id, status: 'generating', progress: created.progress ?? 10, provider: provider.name, providerJobId: created.providerJobId });
  if (created.status === 'failed') throw new Error(created.error ?? 'Media provider failed');
  if (created.status === 'completed') { await complete(job, provider, created); return; }
  for (let attempt = 0; attempt < config.WORKER_MAX_POLLS; attempt++) { await new Promise(resolve => setTimeout(resolve, config.WORKER_INTERVAL_MS)); const current = await provider.getStatus(created.providerJobId); if (current.status === 'failed') throw new Error(current.error ?? 'Media provider failed'); const pct = Math.max(10, Math.min(95, current.progress ?? 10)); await gateway.status({ jobId: job._id, status: current.status === 'completed' ? 'uploading' : 'generating', progress: pct, provider: provider.name, providerJobId: created.providerJobId, outputAssets: current.outputAssets }); await progress(job, `${job.intent === 'image_generation' ? '🎨 Creating your image' : job.intent === 'audio_generation' ? '🎙 Creating your voice' : '🎬 Creating your video'}...\n\n${'█'.repeat(Math.floor(pct / 10))}${'░'.repeat(10 - Math.floor(pct / 10))} ${pct}%`); if (current.status === 'completed') { await complete(job, provider, current); return; } }
  throw new Error(`Media provider job timed out after ${Math.round((config.WORKER_MAX_POLLS * config.WORKER_INTERVAL_MS) / 60000)} minutes`);
}
async function complete(job: WorkerJob, provider: MediaProvider, result: { providerJobId: string; outputAssets?: MediaAsset[] }) { const outputAssets = result.outputAssets ?? []; const outputUrl = outputAssets.find(asset => asset.uri)?.uri; await gateway.status({ jobId: job._id, status: 'completed', progress: 100, provider: provider.name, providerJobId: result.providerJobId, outputUrl, outputAssets }); await progress(job, '✅ Your media is ready. Sending it now...'); if (!job.telegramChatId) return; for (const output of outputAssets) { if (output.type === 'video' && output.uri) await telegram.sendVideo(job.telegramChatId, output.uri, '🎬 Your video is ready.'); else if (output.type === 'image' && output.uri) await telegram.sendPhoto(job.telegramChatId, output.uri, '🖼 Your image is ready.'); else if (output.type === 'audio' && output.uri) await telegram.sendAudio(job.telegramChatId, output.uri, '🎙 Your audio is ready.'); else if (output.uri) await telegram.sendDocument(job.telegramChatId, output.uri, '📄 Your file is ready.'); } }
async function loop() { if (!config.CONVEX_URL || !config.AGENT_GATEWAY_SECRET || !config.TELEGRAM_BOT_TOKEN || !config.STORAGE_BUCKET || !config.STORAGE_ACCESS_KEY || !config.STORAGE_SECRET_KEY) throw new Error('Worker requires Convex, Telegram, and S3 configuration'); for (;;) { try { const claimed = await gateway.claim(); if (!claimed.job) { await new Promise(resolve => setTimeout(resolve, config.WORKER_INTERVAL_MS)); continue; } try { await processJob(claimed.job, claimed.assets); } catch (error) { const reason = error instanceof Error ? error.message : 'Worker failed'; await gateway.fail(claimed.job._id, reason); await progress(claimed.job, `❌ Media job failed: ${reason}`); } } catch (error) { console.error('Worker loop error:', error); await new Promise(resolve => setTimeout(resolve, config.WORKER_INTERVAL_MS * 2)); } } }
loop().catch(error => { console.error(error); process.exit(1); });
